# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'SwiftLinkPreviewExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLinkPreviewExample
  pod 'ImageSlideshow/SDWebImage'
  pod 'SwiftLinkPreview', :path => '../'

end
